### ISSUE TITLE
Develop a way to present bigger content

### ISSUE THREAD

**Issue by svroonland** [code-star/codestar-website#19]
The current website format does not really allow for bigger articles. Would be nice if we can link snippets to a new page / modal with room for an article.

**Comment by mdvanes** [comment]
Also look into adding pages.

**Comment by mdvanes** [comment]
![mockup_article_view](https://cloud.githubusercontent.com/assets/4253562/26596494/2c73da74-456f-11e7-87cb-a76108ba1676.png)

This is a mockup of a possible article view. When clicking on the button under the initial text everything slides to the left. This works mainly like the Job Opportunities page.
