### ISSUE TITLE
Mobile: wegklikken dialoog

### ISSUE THREAD

**Issue by svroonland** [code-star/codestar-website#22]
@mdvanes Can you fill in a short description?

**Comment by mdvanes** [comment]
I was not the person who found this bug. It might have been Maurits or Samuel.

**Comment by mvdam** [comment]
On a small screen, i.e. an iPhone 5 with 320x568 resolution, when you open a job offer and you want to close it; the site menu is activated instead. Also when you click anywhere out of the dialog nothing happens.
