### ISSUE TITLE
Build op CircleCI mislukt altijd

### ISSUE THREAD

**Issue by wernerdegroot** [code-star/codestar-website#3]
Mislukt op:

```
npm test

> codestar-website@0.0.1 test /home/ubuntu/codestar-website
> karma start build/karma.conf.js --single-run

sh: 1: karma: not found
npm ERR! Test failed.  See above for more details.

npm test returned exit code 1
```

**Comment by mdvanes** [comment]
Ik krijg dit lokaal ook met `npm run test`. Dit kwam doordat karma niet in de devdependencies stond. Daarna een fout dat er geen karma.conf.js was, deze zou in /build moeten staan. Ook zijn er geen tests.

De missende packages heb ik toegevoegd aan de package.json, en ook een karma.conf.js en een basis test case.

Ik heb een push gedaan van mijn brach, maar aangezien ik niet kan inloggen op CircleCI kan ik dit niet testen.

**Comment by mdvanes** [comment]
Ik krijg nu:

`ERROR in ./app/libs/pointer_events_polyfill.js
Module not found: Error: Cannot resolve module 'jquery' in /home/martin/ZNoBackup/codestar-website/app/libs
 @ ./app/libs/pointer_events_polyfill.js 1:0-17
`

Op Circle CI en ook lokaal als ik node 4.2.6 gebruik (conform Circle CI). Waarschijnlijk moet een nieuwe npm versie gebruikt worden (hoger dan 3). Het is mogelijk om de node versie te specificeren met een circleci.yml. Lokaal werkt het wel met node 6.9.4.

**Comment by mdvanes** [comment]
Het lijkt in deze branch te werken: https://github.com/code-star/codestar-website/pull/6
